swagger: "2.0"
info:
  description: "This is a API Doc for Brother Printer."
  version: "1.0.0"
  title: "Brother Printer"
basePath: "/file"
schemes:
  - "http"
paths:
  /commandxml/add:
    post:
      tags:
        - "ScanToEmail"
      summary: "Add a new Scan To Email"
      description: ""
      operationId: "addPet"
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/ScanToEmail"
      responses:
        405:
          description: "Invalid input"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
  /commandxml:
    post:
      tags:
        - "ScanToEmail"
      summary: "Get Scan To Email xml (Touch pad with button or Button)"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/text"
      responses:
        405:
          description: "Invalid input"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
  /commandxml/sendToMail:
    post:
      tags:
        - "ScanToEmail"
      summary: "Get Scan To Email xml"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/xml"
        - "application/text"
      responses:
        405:
          description: "Invalid input"
      security:
        - petstore_auth:
            - "write:pets"
            - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  ScanToEmail:
    type: "object"
    properties:
      ScanToEmail:
        type: "object"
        properties:
          Destination:
            type: "string"
          ScanTray:
            type: "string"
          ColorMode:
            type: "string"
          Resolution:
            type: "string"
          FileType:
            type: "string"
    xml:
      name: "ScanToEmail"
